main_app/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

# New url pattern below
urlpatterns = [
    path('', views.home, name='homepage'),
    path('auth/signup/', views.signup, name='signup'),
    path('auth/login/', auth_views.LoginView.as_view(template_name='registration/login.html', redirect_authenticated_user=True), name='login'),
    path('auth/logout/', auth_views.LogoutView.as_view(template_name='registration/signup.html'), name='logout'),
    path('restaurants/', views.restaurants, name='restaurants'),
    path('dashboard/', views.dashboard, name='user_dashboard'),
    path('profile/', views.update_user_info, name='update_user_info'),
    path('restaurants/<int:restaurant_id>/', views.restaurant_detail, name='rdetail'),
    path('restaurants/new-restaurant/', views.RestaurantCreate.as_view(), name='rnew'),
    path('restaurants/<int:restaurant_id>/reservations/create', views.create_reservation, name='newReservation'),
    path('restaurants/<int:restaurant_id>/add-menu/', views.add_menu, name='add_menu'),
]

restaurantCMS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import datetime
from django.core.validators import MaxValueValidator, MinValueValidator
from django.urls import reverse

class Restaurant(models.Model):
  name = models.CharField(max_length=100)
  location = models.CharField(max_length=100)
  max_capacity = models.IntegerField()
  current_capacity = models.IntegerField(default=0)
  owner = models.ForeignKey(User, on_delete=models.CASCADE)
  rating = models.IntegerField(default=5,validators=[MinValueValidator(0),MaxValueValidator(5)])
  opening_time = models.IntegerField(default=9,validators=[MinValueValidator(0),MaxValueValidator(24)])
  closing_time = models.IntegerField(default=23,validators=[MinValueValidator(0),MaxValueValidator(24)])
  description = models.CharField(default="",max_length=250)
  
  def __str__(self):
      return self.name
  
  def get_absolute_url(self):
      return reverse('detail', kwargs={'restaurant_id': self.id})
    
  def get_current_capacity(self):
    return self.max_capacity

  def is_space_available(self, reservation):
    if self.max_capacity > int(reservation['guest_num']):
      return True
    else:
      return False

  def update_capacity(self, reservation):
    self.max_capacity -= int(reservation['guest_num'])
    return self.max_capacity

class Menu(models.Model):
  restaurant = models.ForeignKey(Restaurant,on_delete=models.CASCADE)
  name = models.CharField(max_length=100)
  price = models.DecimalField(max_digits=5,decimal_places=2)
  description = models.CharField(max_length=500)
  
  def __str__(self):
      return self.name

class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	location = models.CharField(max_length=100, null=True, blank=True)
	first_name = models.CharField(max_length=50, null=True, blank=True) 
	last_name = models.CharField(max_length=50, null=True, blank=True)
	phone = models.IntegerField(null=True, blank=True)
	createdAt = models.DateTimeField(default=datetime.now)

	def __str__(self):
		return self.user.username

class Reservation(models.Model):
  customer = models.ForeignKey(User, on_delete=models.CASCADE)
  restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
  guest_num = models.IntegerField(default=1)
  note = models.CharField(default="", max_length=300, null=True, blank=True)
  menu_item = models.ForeignKey(Menu, null=True, blank=True, on_delete=models.SET_NULL)
  booking_date = models.DateTimeField(default=datetime.now)
  booking_time = models.IntegerField(default=16,validators=[MinValueValidator(16),MaxValueValidator(23)])

main_app/forms.py
from .models import Profile, Restaurant, Menu, Reservation
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
	email = forms.EmailField()

	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

class UserUpdateForm(ModelForm):
	email = forms.EmailField()

	class Meta:
		model = User
		fields = ['username', 'email']

class ProfileCreateForm(ModelForm):
	class Meta:
		model = Profile
		fields = ['first_name', 'last_name', 'phone', 'location']
    
class ReservationCreateForm(forms.ModelForm):
	guest_num = forms.IntegerField()
	booking_date = forms.DateField()
	booking_time = forms.IntegerField()
	note = forms.CharField(widget=forms.Textarea(attrs={'rows':2, 'cols':10}))

	class Meta:
		model = Reservation
		fields = ['guest_num', 'booking_date', 'booking_time', 'note']

class MenuForm(ModelForm):
  class Meta:
    model = Menu
    fields = ['name', 'price', 'description']

main_app/views.py
from .models import Profile, Restaurant, Reservation, Menu
from django.views.generic.edit import CreateView
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.shortcuts import render, redirect
from .forms import UserRegisterForm, ProfileCreateForm, UserUpdateForm, ReservationCreateForm, MenuForm

def home(request):
  restaurants = Restaurant.objects.all()
  return render(request, 'index.html', {'restaurants': restaurants})

def restaurants(request):
  restaurants = Restaurant.objects.all()
  return render(request, 'restaurant/index.html', { 'restaurants': restaurants })

def restaurant_detail(request, restaurant_id):
  restaurant = Restaurant.objects.get(id=restaurant_id)
  form = ReservationCreateForm()
  menu_form = MenuForm()
  location = restaurant.location.replace(" ","+")
  return render(request, 'restaurant/detail.html', { 'restaurant': restaurant, 'menu_form': menu_form, 'location':location, 'reservationForm': form })

def add_menu(request, restaurant_id):
    form = MenuForm(request.POST)
    if form.is_valid():
      new_menu = form.save(commit=False)
      new_menu.restaurant_id = restaurant_id
      new_menu.save()
    return redirect('rdetail', restaurant_id=restaurant_id)

class RestaurantCreate(LoginRequiredMixin, CreateView):
  model = Restaurant
  template_name = 'restaurant/new.html'
  fields = ['name', 'location', 'max_capacity', 'opening_time', 'closing_time', 'description']

  def form_valid(self, form):
    form.instance.owner = self.request.user
    return super().form_valid(form)

  success_url = '/restaurants/'

def signup(request):
  if request.method == 'POST':
    form = UserRegisterForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      Profile.objects.create(user_id=user.id)
      # username = form.cleaned_data('username')
      messages.success(request, "signup was successful...")
      return redirect('/auth/login/')
  else:
    # A bad POST or a GET request, so render signup.html with an empty form
    form = UserRegisterForm()
  context = {'form': form}
  return render(request, 'registration/signup.html', context)

@login_required
def dashboard(request):
  user_reservations = Reservation.objects.filter(customer=request.user)
  user_restaurants = Restaurant.objects.filter(owner=request.user)
  usr_form = UserUpdateForm(instance=request.user)
  p_form = ProfileCreateForm(instance=request.user.profile) 
  context = { 'userForm': usr_form, 'profileForm': p_form, "restaurants": user_restaurants, 
  "reservations": user_reservations}
  return render(request, 'user/dashboard.html', context)

@login_required
def update_user_info(request):
  # usr_form = UserUpdateForm(request.POST, instance=request.user)
  if request.method == 'POST':
    usr_form = UserUpdateForm(request.POST, instance=request.user)
    p_form = ProfileCreateForm(request.POST, instance=request.user.profile)
    if usr_form.is_valid() and p_form.is_valid():
      user_form = usr_form.save()
      prof_form = p_form.save()

      messages.success(request, "Profile update was successful...")
    return redirect('user_dashboard')

@login_required
def create_reservation(request, restaurant_id):
  form = ReservationCreateForm(request.POST)
  restaurant = Restaurant.objects.get(id=restaurant_id)
  
  if form.is_valid():
    reservation_data = form.cleaned_data
    if restaurant.is_space_available(reservation_data):
      updated_capacity = restaurant.update_capacity(reservation_data)
      new_reservation = form.save(commit=False)
      new_reservation.customer = request.user
      new_reservation.restaurant = restaurant
      new_reservation.save()
      restaurant.save()
      messages.success(request, "Your reservation has been received.")
      return redirect(f'/restaurants/{restaurant_id}/')
    else:
      messages.error(request, "Reservation currently not accepted by this restaurant.")
      return redirect(f'/restaurants/{restaurant_id}/')
    
    

main_app/templates/restaurant/detail.html
{% extends 'base2.html' %}
{% load crispy_forms_tags %}
{% block mainContent %}
<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <div class="form-wrapper">
                <h1 class="title">Restaurant Details</h1><hr>
                <ul class="list-group">
                    <li class="list-group-item">
                        <span class="heading"><b>Name: </b></span>
                        <span>{{ restaurant.name }}</span>
                    </li>
                    
                    <li class="list-group-item">
                        <span class="heading"><b>Location: </b></span>
                        <a href="https://www.google.com/maps/search/{{ location }}" target="_blank"><h2>{{restaurant.location}}</h2></a>
                    </li>
                    
                    <li class="list-group-item">
                        <span class="heading"><b>Capacity: </b></span>
                        <span>{{ restaurant.max_capacity }}</span>
                    </li>
                    
                    <li class="list-group-item">
                        <span class="heading"><b>Rating: </b></span>
                        <span>{{ restaurant.rating }}</span>
                    </li>
                    
                    <li class="list-group-item">
                        <span class="heading"><b>Description: </b></span>
                        <p class="lead">{{ restaurant.description }}</p>
                    </li>
                    
                    <li class="list-group-item">
                        <span class="heading"><b>Hours of Operation: </b></span>
                        {% if restaurant.opening_time < 12 %}
                        
                        {{restaurant.opening_time}}:00 AM
                        
                        {% else %}
                        
                        {{restaurant.opening_time|add:"-12"}}:00 PM
                        
                        {% endif %}
                        -
                        {% if restaurant.closing_time < 12 %}
                        
                        {{restaurant.closing_time}}:00 AM
                        
                        {% else %}
                        
                        {{restaurant.closing_time|add:"-12"}}:00 PM
                        
                        {% endif %}  
                    </li>
                    
                    {% if restaurant.owner == request.user %}
                    <li class="list-group-item"> 
                            <div>
                                    <h2>add menu item</h2>
                                    <form action="{% url 'add_menu' restaurant.id %}" method="post">
                                        {% csrf_token %}
                                        {{ menu_form.as_p }}
                                        <input type="submit" class="btn" value="Add Menu Item">
                                    </form>
                                </div>
                    </li>
                    {% endif %}

                    <li class="list-group-item">   
                        <div>
                            {%if restaurant.menu_set.all.count > 0%}
                            <h2 class="display-3">menu</h2>
                            {% endif %}
                            <table class="table w-90">
                                {% for menuitem in restaurant.menu_set.all %}   
                                <tr>
                                    <td>
                                        <table class="table-borderless">
                                            <tr>
                                                <td><h3>{{menuitem.name}}  </h3></td>
                                                
                                            </tr>
                                            <tr>
                                                <td>{{menuitem.description}}</td>
                                            </tr>
                                        </table>
                                    </td>            
                                    <td><h3>${{menuitem.price}}</h3></td> 
                                </tr>  
                                {% endfor %}
                            </table>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        {% if restaurant.owner != request.user %}
        <div class="col-sm-6">
            <div class="restaurant-reservation-form">
                <div class="form-wrapper">
                    <h1 class="title text-center">Make Reservation</h1><hr>
                    {% if user.is_authenticated%}
                    <form class="form" action="{% url 'newReservation' restaurant.id %}" method="POST" >
                        {% csrf_token %}
                        {{ reservationForm| crispy }}
                        <input type="submit" value="Reserve" class="btn btn-success btn-block"><hr>
                        <input type="hidden" name="next" value="{{ next }}">
                    </form>
                    {% else %}
                    <h2 class="text-center bg-danger text-white">Please Login to make a reservation.</h2>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

main_app/templates/restaurant/index.html
{% extends 'base2.html' %}
{% load static %}
{% block mainContent %}
	<div class="grid-wrapper">
		<div class="restaurants-list">
			{% for restaurant in restaurants %}
				<div class="restaurants-list_item">
					<div class="restaurant-img" style="background-image: url({% static 'img/img1.jpg' %});"></div>
					<div class="restaurant-desc">
						<h4>{{ restaurant.name }}</h4>
						<p>{{ restaurant.description| truncatechars:40 }}</p>
						<h3 class="text-center"><a href="{% url 'rdetail' restaurant.id %}" class="btn btn-link btn-link-ghost">View Menu</a></h3>
					</div>
				</div>
			{% endfor %}
		</div>
	</div>
{% endblock %}

main_app/templates/restaurant/new.html
{% extends 'base2.html' %}
{% load crispy_forms_tags %}
{% block mainContent %}
<div class="container">
	<div class="row">
		<div class="col-sm-9 offset-sm-2">
			<div class="form-wrapper">
				<h1 class="title text-center">Add New Restaurant</h1><hr>
	      <form class="form" action="{% url 'login' %}" method="POST" class='form'>
					{% csrf_token %}

					{{ form| crispy }}
	        <input type="submit" value="Submit" class="btn btn-success btn-block">
					
					<hr>
					<input type="hidden" name="next" value="{{ next }}">
	      </form>
	    </div>
    </div>
	</div>
</div>
{% endblock %}